// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin melihat seluruh rental order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Order Approve"
                ],
                "summary": "Get All Orders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/admin/orders/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin menyetujui atau mengubah status rental order user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Order Approve"
                ],
                "summary": "Approve Rental Order",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Rental Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Order Status Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_dto.UpdateRentalOrderStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/admin/payments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin melihat seluruh pembayaran",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Payment Approve"
                ],
                "summary": "Get All Payments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/admin/payments/{payment_id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin menyetujui pembayaran rental order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Payment Approve"
                ],
                "summary": "Approve Payment",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Payment ID",
                        "name": "payment_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payment Status Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_dto.UpdatePaymentStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/admin/topups": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin melihat seluruh permintaan top up",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Top Up Approve"
                ],
                "summary": "Get All Top Ups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/admin/topups/{id}/approve": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin menyetujui permintaan top up user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Top Up Approve"
                ],
                "summary": "Approve Top Up",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Top Up ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/users/cameras": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "User melihat daftar kamera yang tersedia untuk rental",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Camera"
                ],
                "summary": "Get All Cameras",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/users/cameras/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "User melihat detail kamera berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Camera"
                ],
                "summary": "Get Camera By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "User melakukan login untuk mendapatkan JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Login"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/users/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendapatkan seluruh order milik user yang sedang login",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Order"
                ],
                "summary": "Get My Orders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "User membuat order rental dengan memilih camera",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Order"
                ],
                "summary": "Create Rental Order",
                "parameters": [
                    {
                        "description": "Rental Order Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_dto.CreateRentalOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/users/orders/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "User melihat detail order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Order"
                ],
                "summary": "Get Order By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Rental Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/users/payments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendapatkan seluruh pembayaran milik user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Payment"
                ],
                "summary": "Get My Payments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "User melakukan pembayaran untuk rental order yang telah disetujui",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Payment"
                ],
                "summary": "Create Payment",
                "parameters": [
                    {
                        "description": "Payment Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_dto.CreatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/users/payments/{payment_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendapatkan detail pembayaran berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Payment"
                ],
                "summary": "Get My Payment By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Payment ID",
                        "name": "payment_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "User melakukan registrasi akun",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Register"
                ],
                "summary": "Register User",
                "parameters": [
                    {
                        "description": "Register Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/users/topup/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendapatkan detail top up berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Top Up"
                ],
                "summary": "Get Top Up By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Top Up ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/users/topups": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "User melihat riwayat top up miliknya",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Top Up"
                ],
                "summary": "Get My Top Ups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "User membuat permintaan top up saldo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User - Top Up"
                ],
                "summary": "Create Top Up",
                "parameters": [
                    {
                        "description": "Top Up Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_dto.CreateTopUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mendapatkan data user berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/p2-ip-kartikajls_internal_helper.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "p2-ip-kartikajls_internal_dto.CreatePaymentRequest": {
            "type": "object",
            "required": [
                "payment_method",
                "rental_order_id"
            ],
            "properties": {
                "payment_method": {
                    "type": "string"
                },
                "rental_order_id": {
                    "type": "integer"
                }
            }
        },
        "p2-ip-kartikajls_internal_dto.CreateRentalOrderRequest": {
            "type": "object",
            "required": [
                "camera_id"
            ],
            "properties": {
                "camera_id": {
                    "type": "integer"
                }
            }
        },
        "p2-ip-kartikajls_internal_dto.CreateTopUpRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                }
            }
        },
        "p2-ip-kartikajls_internal_dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "p2-ip-kartikajls_internal_dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "p2-ip-kartikajls_internal_dto.UpdatePaymentStatusRequest": {
            "type": "object",
            "required": [
                "payment_status"
            ],
            "properties": {
                "payment_status": {
                    "type": "string"
                }
            }
        },
        "p2-ip-kartikajls_internal_dto.UpdateRentalOrderStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "p2-ip-kartikajls_internal_helper.Response": {
            "type": "object",
            "properties": {
                "responseCode": {
                    "type": "integer"
                },
                "responseData": {},
                "responseMessage": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan JWT dengan format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Jati Rent Camera API",
	Description:      "REST API untuk aplikasi Rent Camera.\nAPI ini menyediakan fitur register, login, camera, top up, rental order, dan payment.\nAdmin dapat melakukan approval terhadap top up, order, dan payment.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
